import Head from 'next/head'
import Image from 'next/image'

const AppNavBar = props => (
	<div>
	<h4>{props.title}</h4>
	</div>
);
const AppCardBullets = ({date, bullets}) => (
	<div>
		<hr/>
		<h5>{date}</h5>
		<ul>
			{bullets.map(bullet => (
			<li><strong>{bullet.type}</strong>
			{bullet.title}</li>
			))}
		</ul>
		<hr/>
	</div>
);


export default function Home() {
	let title = "Milão APP";
	const bullets_today = [
	{type: 'event', title: 'Momento síncrono e assíncrono sobre componente react'},
	{type: 'task', title: '1. Palavras chaves - bullet journal, github issues'}
];
        const bullets_tomorrow = [];
    return (<div>
        <Head>
        	<title>{title}</title> <meta name = "description" 
		content = "Generated by create next app"/>
        	<link rel = "icon" href = "/favicon.ico"/>
        </Head>

        <main>
        	<h1> Radmila diz: Bem vindo ao meu primeiro app on 
		<a href = "https://nextjs.org" > Next.js! </a></h1>
	<AppNavBar title={title}/>
	{bullets_today.map(item => <p>{item.type} - {item.title}</p>)}
	<p>{bullets_today[0].type} - {bullets_today[0].title}</p>
	<AppCardBullets date={"22/09/2021"} bulltes={bullets_today}/>
	<AppCardBullets date={"29/09/2021"} bulltes={bullets_tomorrow}/>

        </main>
        </div>
    )
}